export const VALVES = [
  {
    valveType: "Butterfly",
    subType: "Aluminum Wafer Type Centric Butterfly Valve",
    sizeRange: "40 MM to 150 MM (1 ½” To 6”)",
    temperatureRange: "-40° C to +120° C",
    pressureRating: "PN10",
    designStandard: "As Per API 609 / BS 5155 / IS 13095",
    faceToFace: "As Per API 609 Cat A / BS 5155 / IS 13095",
    testing: "As per API 589 / IS 13095",
    leakageClass: "VI Tight Shut Off",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Wafer End",
    features:
      "Light weight, corrosion resistant, replaceable seat, low torque and long life",
    materialSpecification: {
      Body: "Aluminum (Pressure Die Casted)",
      "Neck Piece": "SS 304",
      Disc: ["CF8", "CF8M"],
      Seat: ["Nitrile", "EPDM"],
      Stem: ["SS 410", "SS 316"],
      Fasteners: "SS",
    },
    uses: "HVAC Systems (Heat, Ventilation and Air Conditioning) And Water treatment plant",
  },
  {
    valveType: "Butterfly",
    subType: "Wafer Type Centric Butterfly Valve",
    sizeRange: "40 MM to 700 MM (1 ½” To 28”)",
    temperatureRange: "-40° C to +180° C (Depends on material of construction)",
    pressureRating: ["PN10", "PN16"],
    designStandard: "As Per API 609 / BS 5155 / IS 13095",
    faceToFace: "As Per API 609 Cat A / BS 5155 / IS 13095",
    testing: "As per API 589 / IS 13095",
    leakageClass: "VI Tight Shut Off",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Wafer End",
    features:
      "Compact and low cost design, easy installation and maintenance, bonded as well as replaceable seat, long life, Food grade seat available on request",
    materialSpecification: {
      Body: ["CI", "SG", "WCB", "CF8", "CF8M"],
      Disc: ["SG", "WCB", "CF8", "CF8M"],
      Seat: ["Nitrile", "EPDM", "Neoprene", "Silicon", "Viton"],
      Stem: ["SS 410", "SS 316"],
      Fasteners: ["MS", "SS"],
    },
    uses: "HVAC Systems (Heat, Ventilation and Air Conditioning), Waste water treatment plant, Chemical and Petrochemical, Low pressure Oil, Gas and Fuel application, Food and Beverage Industry and Marine application",
  },
  {
    valveType: "Butterfly",
    subType: "Fully Lugged Centric Butterfly Valve",
    sizeRange: "40 MM to 700 MM (1 ½” To 28”)",
    temperatureRange: "-40° C to +180° C (Depends on material of construction)",
    pressureRating: ["PN10", "PN16"],
    designStandard: "As Per API 609 / BS 5155 / IS 13095",
    faceToFace: "As Per API 609 Cat A / BS 5155 / IS 13095",
    testing: "As per API 589 / IS 13095",
    leakageClass: "VI Tight Shut Off",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Lugged End",
    features:
      "Robust design, suitable for dead-end service, replaceable seat, Top Flange suitable to ISO 5211",
    materialSpecification: {
      Body: ["CI", "SG", "WCB", "CF8", "CF8M"],
      Disc: ["SG", "WCB", "CF8", "CF8M"],
      Seat: ["Nitrile", "EPDM", "Neoprene", "Silicon", "Viton"],
      Stem: ["SS 410", "SS 316"],
      Fasteners: ["MS", "SS"],
    },
    uses: "HVAC Systems, Water treatment, Chemical and Petrochemical applications",
  },
  {
    valveType: "Butterfly",
    subType: "Double Flange End Centric Butterfly Valve",
    sizeRange: "50 MM to 1200 MM (2” To 48”)",
    temperatureRange: "-40° C to +180° C (Depends on material of construction)",
    pressureRating: ["PN10", "PN16"],
    designStandard: "As Per API 609 / BS 5155 / IS 13095",
    faceToFace: "As Per API 609 Cat A / BS 5155 / IS 13095",
    testing: "As per API 589 / IS 13095",
    leakageClass: "VI Tight Shut Off",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Flanged End",
    features:
      "Heavy duty design, replaceable seat, Top Flange suitable to ISO 5211",
    materialSpecification: {
      Body: ["CI", "SG", "WCB", "CF8", "CF8M"],
      Disc: ["SG", "WCB", "CF8", "CF8M"],
      Seat: ["Nitrile", "EPDM", "Neoprene", "Silicon", "Viton"],
      Stem: ["SS 410", "SS 316"],
      Fasteners: ["MS", "SS"],
    },
    uses: "Water supply, Oil and Gas, Chemical processing",
  },
  {
    valveType: "Butterfly",
    subType: "Double Offset Wafer Type Butterfly Valve",
    sizeRange: "50 MM to 600 MM (2” To 24”)",
    temperatureRange: "-50° C to +250° C (Depends on material of construction)",
    pressureRating: ["PN10", "PN16", "Class 150"],
    designStandard: "As Per API 609 Category B",
    faceToFace: "As Per API 609",
    testing: "As per API 598",
    leakageClass: "VI Tight Shut Off",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Wafer End",
    features:
      "High performance, double offset design for reduced seat wear, Top Flange suitable to ISO 5211",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Disc: ["WCB", "CF8", "CF8M"],
      Seat: ["PTFE", "RTFE"],
      Stem: ["SS 316", "17-4 PH"],
      Fasteners: "SS",
    },
    uses: "High pressure and temperature applications, Oil and Gas, Chemical industries",
  },
  {
    valveType: "Ball",
    subType: "Screw End 1-Piece Ball Valve",
    sizeRange: "15 MM to 50 MM (½” To 2”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: ["Class 150", "1000 WOG", "22 Kg/Cm²"],
    designStandard: "As Per IS 9890 / BS 5351",
    faceToFace: "Manufacturer’s Standard / ASME B 16.10",
    testing: "As per API 589",
    leakageClass: "ISO 5208 Class VI",
    operation: "Manual Hand Lever",
    endConnection: "Screwed (Threaded) BSP-F",
    features: "Compact, light-weight, low cost",
    materialSpecification: {
      Body: ["CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE", "Carbon Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: "SS",
    },
    uses: "Water / Oil / Gas / Chemical",
  },
  {
    valveType: "Ball",
    subType: "Flange End 1-Piece Ball Valve",
    sizeRange: "25 MM to 100 MM (1” To 4”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: "Class 150",
    designStandard: "As Per ISO 17292 / BS 5351",
    faceToFace: "As Per ASME B 16.10",
    testing: "As per API 589",
    leakageClass: "ISO 5208 Class VI",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Flanged end suitable to mount between ASME B16.5 Flanges",
    features:
      "Compact, leak resistant and cost effective. 65 MM, 80 MM And 100 MM are reduce bore design",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE", "Carbon Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: ["MS", "SS"],
    },
    uses: "Water / Oil / Gas / Chemical",
  },
  {
    valveType: "Ball",
    subType: "Two Piece Ball Valve - Flange End",
    sizeRange: "15 MM to 300 MM (½” To 12”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: ["Class 150", "Class 300"],
    designStandard: "As Per ISO 17292 / BS 5351",
    faceToFace: "As Per ASME B 16.10",
    testing: "As per API 598",
    leakageClass: "ISO 5208 Class VI",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Flanged end suitable to mount between ASME B16.5 Flanges",
    features: "Full bore design, anti-static, blow-out proof stem",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE", "Carbon Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: ["MS", "SS"],
    },
    uses: "Water / Oil / Gas / Chemical / Petrochemical",
  },
  {
    valveType: "Ball",
    subType: "Three Piece Ball Valve - Screw End / Socket End",
    sizeRange: "15 MM to 100 MM (½” To 4”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: ["1000 WOG", "22 Kg/Cm²"],
    designStandard: "As Per ISO 17292 / BS 5351",
    faceToFace: "Manufacturer’s Standard",
    testing: "As per API 598",
    leakageClass: "ISO 5208 Class VI",
    operation: "Manual Hand Lever",
    endConnection: "Screwed (BSP-F) / Socket Weld",
    features: "Full bore, easy maintenance, blow-out proof stem",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE", "Carbon Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: "SS",
    },
    uses: "Water / Oil / Gas / Chemical",
  },
  {
    valveType: "Ball",
    subType: "Three Piece Ball Valve - Flange End",
    sizeRange: "15 MM to 300 MM (½” To 12”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: ["Class 150", "Class 300"],
    designStandard: "As Per ISO 17292 / BS 5351",
    faceToFace: "As Per ASME B 16.10",
    testing: "As per API 598",
    leakageClass: "ISO 5208 Class VI",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Flanged end suitable to mount between ASME B16.5 Flanges",
    features: "Full bore design, anti-static, blow-out proof stem",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE", "Carbon Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: ["MS", "SS"],
    },
    uses: "Water / Oil / Gas / Chemical / Petrochemical",
  },
  {
    valveType: "Ball",
    subType: "Wafer Type Ball Valve",
    sizeRange: "15 MM to 100 MM (½” To 4”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: "Class 150",
    designStandard: "Manufacturer’s Standard",
    faceToFace: "Manufacturer’s Standard",
    testing: "As per API 598",
    leakageClass: "ISO 5208 Class VI",
    operation: ["Manual Hand Lever", "Gearbox", "Actuated"],
    endConnection: "Wafer End",
    features: "Compact design, can be used as flush bottom valve",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: "SS",
    },
    uses: "Chemical / Pharmaceutical / Food processing",
  },
  {
    valveType: "Ball",
    subType: "TC End Ball Valve",
    sizeRange: "15 MM to 50 MM (½” To 2”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: "Class 150",
    designStandard: "Manufacturer’s Standard",
    faceilibre: true,
    faceToFace: "Manufacturer’s Standard",
    testing: "As per API 589",
    leakageClass: "ISO 5208 Class VI",
    operation: "Manual Hand Lever",
    endConnection: "Tri-Clover End (TC End)",
    features: "Sanitary design, easy to clean",
    materialSpecification: {
      Body: ["CF8", "CF8M"],
      Ball: ["SS 304", "SS 316"],
      Seat: ["Virgin PTFE", "Glass Filled PTFE"],
      Stem: ["SS 304", "SS 316"],
      Lever: ["SS 304", "SS 316"],
    },
    uses: "Pharmaceutical / Food & Beverage",
  },
  {
    valveType: "Check",
    subType: "Single Plate Wafer Type Check Valve",
    sizeRange: "50 MM to 600 MM (2” To 24”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: ["PN10", "PN16"],
    designStandard: "As Per API 594",
    faceToFace: "As Per API 594",
    testing: "As per API 598",
    leakageClass: "Class VI",
    operation: "Self-Actuated",
    endConnection: "Wafer End",
    features: "Light weight, short face-to-face dimension",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Disc: ["SS 304", "SS 316"],
      Spring: "SS 316",
    },
    uses: "Water / Oil / Gas",
  },
  {
    valveType: "Check",
    subType: "Disc Check Valve",
    sizeRange: "15 MM to 100 MM (½” To 4”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: "Class 150",
    designStandard: "Manufacturer’s Standard",
    faceToFace: "Manufacturer’s Standard",
    testing: "As per API 598",
    leakageClass: "Class VI",
    operation: "Self-Actuated",
    endConnection: "Screwed (BSP-F) / Flanged",
    features: "Compact design, low pressure drop",
    materialSpecification: {
      Body: ["CF8", "CF8M"],
      Disc: ["SS 304", "SS 316"],
    },
    uses: "Water / Oil / Gas",
  },
  {
    valveType: "Check",
    subType: "Dual Plate Check Valve",
    sizeRange: "50 MM to 600 MM (2” To 24”)",
    temperatureRange: "-40° C to +180° C",
    pressureRating: ["PN10", "PN16", "Class 150"],
    designStandard: "As Per API 594",
    faceToFace: "As Per API 594",
    testing: "As per API 598",
    leakageClass: "Class VI",
    operation: "Self-Actuated",
    endConnection: "Wafer End",
    features: "Non-slam design, low pressure drop",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Plate: ["SS 304", "SS 316"],
      Spring: "SS 316",
    },
    uses: "Water / Oil / Gas / Steam",
  },
  {
    valveType: "Gate",
    subType: "Gate Valve Flange End (Class 150/300/600)",
    sizeRange: "50 MM to 600 MM (2” To 24”)",
    temperatureRange: "-40° C to +425° C",
    pressureRating: "Class 150 / 300 / 600",
    designStandard: "As Per API 600",
    faceToFace: "As Per ASME B16.10",
    testing: "As per API 598",
    leakageClass: "Class VI",
    operation: ["Handwheel", "Gearbox", "Actuated"],
    endConnection: "Flanged end suitable to mount between ASME B16.5 Flanges",
    features: "Rising stem, flexible wedge",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Wedge: ["WCB", "CF8", "CF8M"],
      Seat: "Stellite",
      Stem: "SS 410",
    },
    uses: "Water / Oil / Gas / Steam",
  },
  {
    valveType: "Globe",
    subType: "Globe Valve Flange End (Class 150)",
    sizeRange: "50 MM to 300 MM (2” To 12”)",
    temperatureRange: "-40° C to +425° C",
    pressureRating: "Class 150",
    designStandard: "As Per BS 1873",
    faceToFace: "As Per ASME B16.10",
    testing: "As per API 598",
    leakageClass: "Class VI",
    operation: ["Handwheel", "Gearbox", "Actuated"],
    endConnection: "Flanged end suitable to mount between ASME B16.5 Flanges",
    features: "Throttling capability, outside screw and yoke",
    materialSpecification: {
      Body: ["WCB", "CF8", "CF8M"],
      Disc: ["WCB", "CF8", "CF8M"],
      Seat: "Stellite",
      Stem: "SS 410",
    },
    uses: "Water / Oil / Gas / Steam",
  },
  {
    valveType: "Needle",
    subType: "Thread End Needle Valve",
    sizeRange: "15 MM to 25 MM (½” To 1”)",
    temperatureRange: "-40° C to +200° C",
    pressureRating: "4000 to 6000 Psi",
    designStandard: "Manufacturer’s Standard",
    faceToFace: "Manufacturer’s Standard",
    testing: "Manufacturer’s Standard",
    leakageClass: "Class VI",
    operation: "Manual",
    endConnection: "Screwed (BSP-F)",
    features: "Fine flow control, high pressure capability",
    materialSpecification: {
      Body: ["SS 304", "SS 316"],
    },
    uses: "Instrumentation / Gas / Liquid",
  },
];
